<?php

namespace Amp\Parallel\Ipc;

use Amp\Cancellation;
use Amp\Socket\ResourceSocket;

interface IpcHub
{
    public const DEFAULT_KEY_RECEIVE_TIMEOUT = 5;
    public const DEFAULT_KEY_LENGTH = 64;

    /**
     * @param string $key A key generated by {@see generateKey()}.
     * @param Cancellation|null $cancellation
     *
     * @return ResourceSocket
     */
    public function accept(string $key, ?Cancellation $cancellation = null): ResourceSocket;

    public function isClosed(): bool;

    public function close(): void;

    public function getUri(): string;

    public function generateKey(): string;
}
