<?php

namespace Amp\Parallel\Ipc;

use Amp\Cancellation;
use Amp\Socket\Socket;

interface IpcHub
{
    public const DEFAULT_KEY_RECEIVE_TIMEOUT = 5;
    public const DEFAULT_KEY_LENGTH = 64;

    /**
     * @param non-empty-string $key A key generated by {@see generateKey()}.
     */
    public function accept(string $key, ?Cancellation $cancellation = null): Socket;

    public function isClosed(): bool;

    public function close(): void;

    /**
     * @return non-empty-string URI to use with {@see connect()}.
     */
    public function getUri(): string;

    /**
     * @return non-empty-string Pass the key returned from this method to the connecting context and {@see accept()}.
     */
    public function generateKey(): string;
}
