<?php
namespace Icicle\Concurrent\Threading;

use Icicle\Concurrent\ContextInterface;
use Icicle\Concurrent\Exception\ContextAbortException;
use Icicle\Promise;
use Icicle\Socket\Stream\DuplexStream;

/**
 * Implements an execution context using native multi-threading.
 *
 * The thread context is not itself threaded. A local instance of the context is
 * maintained both in the context that creates the thread and in the thread
 * itself.
 */
class ThreadContext implements ContextInterface
{
    /**
     * @var \Thread A thread instance.
     */
    public $thread;

    /**
     * @var Promise\Deferred A deferred object that resolves when the context ends.
     */
    private $deferredJoin;

    /**
     * @var DuplexStream An active socket connection to the thread's socket.
     */
    private $socket;

    /**
     * @var A reference handle to the invoker.
     */
    private $invoker;

    /**
     * Creates an instance of the current context class for the local thread.
     *
     * @return self
     *
     * @internal
     */
    final public static function createLocalInstance(Thread $thread)
    {
        $class = new \ReflectionClass(static::class);
        $instance = $class->newInstanceWithoutConstructor();
        $instance->thread = $thread;
        return $instance;
    }

    /**
     * Creates a new thread context.
     *
     * @param callable $function The function to run in the thread.
     */
    public function __construct(callable $function)
    {
        $this->deferredJoin = new Promise\Deferred(function () {
            $this->kill();
        });

        $this->thread = new Thread($function);
        $this->thread->autoloaderPath = $this->getComposerAutoloader();
    }

    /**
     * {@inheritdoc}
     */
    public function isRunning()
    {
        return $this->thread->isRunning();
    }

    /**
     * {@inheritdoc}
     */
    public function start()
    {
        if (($sockets = stream_socket_pair(STREAM_PF_UNIX, STREAM_SOCK_STREAM, STREAM_IPPROTO_IP)) === false) {
            throw new \Exception();
        }

        $this->thread->initialize($sockets[1]);
        $this->thread->start(PTHREADS_INHERIT_INI);

        $this->socket = new DuplexStream($sockets[0]);

        $this->socket->read(1)->then(function ($data) {
            $message = ord($data);
            if ($message === Thread::MSG_DONE) {
                $this->deferredJoin->resolve();
                $this->thread->join();
                return;
            }

            // Get the fatal exception from the process.
            return $this->socket->read(2)->then(function ($data) {
                $serializedLength = unpack('S', $data);
                $serializedLength = $serializedLength[1];
                return $this->socket->read($serializedLength);
            })->then(function ($data) {
                $previous = unserialize($data);
                $exception = new ContextAbortException('The context encountered an error.', 0, $previous);
                $this->deferredJoin->reject($exception);
                $this->socket->close();
            });
        }, function (\Exception $exception) {
            $this->deferredJoin->reject($exception);
        });
    }

    /**
     * {@inheritdoc}
     */
    public function stop()
    {
        $this->thread->kill();
    }

    /**
     * {@inheritdoc}
     */
    public function kill()
    {
        $this->thread->kill();
    }

    /**
     * {@inheritdoc}
     */
    public function join()
    {
        return $this->deferredJoin->getPromise();
    }

    /**
     * {@inheritdoc}
     */
    public function lock()
    {
        $this->thread->lock();
    }

    /**
     * {@inheritdoc}
     */
    public function unlock()
    {
        $this->thread->unlock();
    }

    /**
     * {@inheritdoc}
     */
    public function synchronized(callable $callback)
    {
        $this->lock();

        try {
            $returnValue = $callback($this);
        } finally {
            $this->unlock();
        }

        return $returnValue;
    }

    /**
     * Gets the full path to the Composer autoloader.
     *
     * If no Composer autoloader is being used, `null` is returned.
     *
     * @return \Composer\Autoload\ClassLoader|null
     */
    private function getComposerAutoloader()
    {
        foreach (get_included_files() as $path) {
            if (strpos($path, 'vendor/autoload.php') !== false) {
                $source = file_get_contents($path);
                if (strpos($source, '@generated by Composer') !== false) {
                    return $path;
                }
            }
        }

        return null;
    }
}
